from django.conf.urls import url
from emogo.apps.stream import views

urlpatterns = [
    # url(r'^/stream/collaborators/(?P<pk>[0-9]+)/', views.StreamAPI.as_view(fields=), name='user-list')
    url(r'^load_test_api/$', views.LoadTestView.as_view()),
    url(r'^streams/(?P<stream_id>[0-9]+)/delete_comments/$',
        views.DeleteStreamComments.as_view()),
    url(r'^stream-search-for-add-content/', views.SearchEmogoAPI.as_view()),
    url(r'^stream/collaborator/(?P<pk>[0-9]+)/$', views.StreamAPI.as_view(), name='stream_collaborator'),
    url(r'^stream/(?P<pk>[0-9]+)/$', views.StreamAPI.as_view(), name='view_stream'),
    url(r'^stream/$', views.StreamAPI.as_view()),
    url('^stream', views.StreamAPI.as_view()),
    url(r'^emogo-move-to-folder/(?P<pk>[0-9]+)/$', views.StreamMoveToFolderAPI.as_view()),
    url('^like_dislike_stream', views.StreamLikeDislikeAPI.as_view()),
    url(r'^like_stream/(?P<stream_id>[0-9]+)/$', views.StreamLikeAPI.as_view()),
    url('^like_dislike_content', views.ContentLikeDislikeAPI.as_view()),
    url('^increase_view_count', views.IncreaseStreamViewCount.as_view()),
    # The API is created because developer unable to get link type content
    url(r'^delete_content/$', views.DeleteContentInBulk.as_view()),
    url(r'^content/link_type/$', views.LinkTypeContentAPI.as_view()),
    url(r'^content/(?P<pk>[0-9]+)/$', views.ContentAPI.as_view()),
    url(r'^content/$', views.ContentAPI.as_view()),
    url(r'^copy_content/$', views.CopyContentAPI.as_view()),
    url(r'^get_top_content/$', views.GetTopContentAPI.as_view()),
    url(r'^get_top_twenty_content/$', views.GetTopTwentyContentAPI.as_view()),
    url(r'^move_content_to_stream/$', views.MoveContentToStream.as_view()),
    url(r'^reorder_stream_content/$', views.ReorderStreamContent.as_view()),
    url(r'^reorder_content/$', views.ReorderContent.as_view()),
    url(r'^extremist_report/$', views.ExtremistReportAPI.as_view()),
    url(r'^ranjeet/$', views.TestUrlAPI.as_view()),
    url(r'^delete_stream_content/(?P<pk>[0-9]+)/$', views.DeleteStreamContentAPI.as_view()),
    url(r'^bulk_delete_stream_content/(?P<pk>[0-9]+)/$', views.DeleteStreamContentInBulkAPI.as_view()),
    url(r'^bulk_contents', views.ContentInBulkAPI.as_view()),
    url(r'^content/share_extension', views.ContentShareExtensionAPI.as_view()),
    url(r'^recent_updates/$', views.RecentUpdatesAPI.as_view()),
    url(r'^recent_updates_detail/$', views.RecentUpdatesDetailListAPI.as_view()),
    url(r'^seen_index/$', views.SeenIndexAPI.as_view()),
    url(r'^starred_streams', views.StarredAPI.as_view()),
    url(r'^bookmarks/(?P<stream_id>[0-9]+)/$', views.StarredAPI.as_view()),  # don't make a name starts with stream
    url(r'^bookmarks/$', views.StarredAPI.as_view()),# don't make a name starts with stream
    url(r'^bookmarks_and_new_emogos/$', views.BookmarkNewEmogosAPI.as_view()),
    url(r'^new_emogos_list', views.NewEmogosAPI.as_view()),
    url(r'^update_user_view_stream_status/$', views.AddUserViewStreamStatus.as_view()),
    url(r'^user_liked_content/$', views.UserLikedContentAPI.as_view()),
    url(r'^content_not_yet_added/$', views.NotYetAddedContentAPI.as_view()),
    url(r'^folder/(?P<pk>[0-9]+)/$', views.FolderAPI.as_view()),
    url(r'^folder/$', views.FolderAPI.as_view()),
    url(r'^share-content-in-imessage/$', views.ContentShareInImessageAPI.as_view()),
    # in get_stream_content url, the pk is contnet id
    # url(r'^get_stream_content/(?P<stream_id>[0-9]+)/(?P<pk>[0-9]+)/$',
    #     views.GetStreamContentAPI.as_view()),
    url(r'^get_stream_content/$', views.GetStreamContentAPI.as_view()),
    url(r'^get_open_stream_content/$', views.GetOpenStreamContentAPI.as_view()),
]
