# Uncomment the next line to define a global platform for your project
xcodeproj 'Emogo.xcodeproj'

platform :ios, '9.0'
inhibit_all_warnings!
def common_pods_for_target
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'SwiftyJSON'
    pod 'AWSS3'
    
end


target 'Emogo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Emogo
    common_pods_for_target
    pod 'IQKeyboardManagerSwift'
    pod "SwiftyCam"
    pod "ESPullToRefresh"
    pod 'Fabric'
    pod 'Crashlytics'
pod 'Gallery'
    pod 'ReadabilityKit'


    target 'EmogoTests' do
        inherit! :search_paths
        common_pods_for_target
        pod 'IQKeyboardManagerSwift'
        
        # Pods for testing
    end
    
    target 'EmogoUITests' do
        inherit! :search_paths
        # Pods for testing
        common_pods_for_target
        pod 'IQKeyboardManagerSwift'
        
    end
    
    
    
end

target 'iMessageExt' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for iMessageExt
    common_pods_for_target
end

target 'ShareExt' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for ShareExt
    
end
