# Uncomment the next line to define a global platform for your project
xcodeproj 'Emogo.project'

platform :ios, '9.0'
inhibit_all_warnings!
def common_pods_for_target
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'SwiftyJSON'
    pod 'AWSS3'
    pod 'Lightbox'
    pod 'Presentr'
    pod "GSKStretchyHeaderView"
    pod "Haptica"
    pod "SkeletonView"
    pod "BPCircleActivityIndicator"

end


target 'Emogo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Emogo
    common_pods_for_target
    
    pod "SwiftyCam"
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'IQKeyboardManagerSwift'
    pod 'GiphyCoreSDK'
    pod 'XLActionController'
    pod 'CropViewController'
    pod 'SwiftLinkPreview'
    pod ‘RS3DSegmentedControl’
    pod 'Branch'
    pod 'PryntTrimmerView'
    pod 'BMPlayer'
    pod "Haptica"
    pod "RichEditorView"
    pod 'DropDown'
pod 'SwiftMessages'

    target 'EmogoTests' do
        inherit! :search_paths
        common_pods_for_target
        
        # Pods for testing
    end
    
    target 'EmogoUITests' do
        inherit! :search_paths
        # Pods for testing
        common_pods_for_target
        
    end
    
    
end

target 'iMessageExt' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for iMessageExt
    common_pods_for_target
end

target 'ShareExt' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'SDWebImage'
    pod 'SwiftLinkPreview'
    
    # Pods for ShareExt
    
end
